name: Build linux-x86

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: apt update
      run: sudo apt-get update

    - name: install xorg-dev
      run: sudo apt-get install -y xorg-dev

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Debug -DSL_DOWNLOAD_DATA=OFF -DSL_BUILD_WITH_KTX=OFF -DSL_BUILD_WITH_MEDIAPIPE=OFF

    - name: Build
      run: cmake --build ${{ github.workspace }}/build
