name: Build g2o

on:
  workflow_dispatch:
  push:
    branches:
      - build-workflow

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Download QT
      run: curl.exe https://download.qt.io/official_releases/qt/5.15/5.15.11/single/qt-everywhere-opensource-src-5.15.11.tar.xz -o qt.tar.xz

    - name: unpack QT
      run: tar xJf qt.tar.xz

    - name: configure QT
      working-directory: qt-everywhere-src-5.15.11
      run: ./configure -debug -nomake examples -nomake tests -skip qtwebengine -opensource

    - name: build QT
      working-directory: qt-everywhere-src-5.15.11
      run: nmake

    - name: Run build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_g2o_x64.bat

    - name: Archive prebuilt g2o
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-g2o
        path: ${{ github.workspace }}/externals/prebuild_scripts/g2o


