name: Build Dependancy Assimp

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Run build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_assimp_for_linux.sh v5.4.0

    - name: Archive prebuilt assimp 
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-assimp-linux
        path: ${{ github.workspace }}/externals/prebuilt/linux_assimp_v5.4.0


    - name: Run andv8 build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_assimp_for_andV8.sh v5.4.0

    - name: Archive prebuilt assimp 
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-assimp-android
        path: ${{ github.workspace }}/externals/prebuilt/andV8_assimp_v5.4.0

