name: Build Windows

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Run build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_g2o_x64.bat

    - name: Archive prebuilt g2o
        uses: actions/upload-artifact@v3
        with:
          name: prebuilt g2o
          path: ${{ github.workspace }}/externals/prebuild_scripts/g2o


