name: Build MacOS

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build ${{ github.workspace }}/build
