name: Build Openssl

on:
  workflow_dispatch:
  push:
    branches:
      - build-workflow

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Run build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_openssl_for_win64.bat

    - name: Archive prebuilt g2o
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-openssl-windows
        path: ${{ github.workspace }}/externals/prebuilt/win64_openssl

  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Run build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_openssl_for_linux.sh

    - name: Archive prebuilt linux
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-openssl-linux
        path: ${{ github.workspace }}/externals/prebuilt/linux_openssl_1.1.1h
  build-macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Run build script intel
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: arch -x86_64 ./build_openssl_for_mac64_and_iosV8.sh

    - name: Archive prebuilt openssl intel
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-openssl-mac64
        path: ${{ github.workspace }}/externals/prebuilt/mac64_openssl_1.1.1g

    - name: Archive prebuilt openssl ios
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-openssl-ios
        path: ${{ github.workspace }}/externals/prebuilt/iosV8_openssl_1.1.1g
