name: Build dependancy OpenSSL

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: ilammy/setup-nasm@v1

    #- name: Install winget
    #  uses: Cyberboss/install-winget@v1

    #- name: Install nasm
    #  run: winget install -e --id NASM.NASM
    #- name: Download nasm
    #  uses: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip

    #- name: Choco install nasm
    #  uses: crazy-max/ghaction-chocolatey@v3
    #  with: 
    #    args: install nasm

    - name: Run build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_openssl_for_win64.bat

    - name: Archive prebuilt openssl windows
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-openssl-windows
        path: ${{ github.workspace }}/externals/prebuilt/win64_openssl

  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Run build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_openssl_for_linux.sh

    - name: Archive prebuilt linux
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-openssl-linux
        path: ${{ github.workspace }}/externals/prebuilt/linux_openssl_3.2.1

  build-android:
    runs-on: ubuntu-22.04
    steps:
    - name: Run android build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_openssl_for_andV8.sh

    - name: Archive prebuilt andV8
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-openssl-andV8
        path: ${{ github.workspace }}/externals/prebuilt/andV8_openssl_3.2.1
  build-macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Run build script intel
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: arch -x86_64 ./build_openssl_for_mac64_and_iosV8.sh

    - name: Archive prebuilt openssl intel
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-openssl-mac64
        path: ${{ github.workspace }}/externals/prebuilt/mac64_openssl_3.2.1

    - name: Archive prebuilt openssl ios
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-openssl-ios
        path: ${{ github.workspace }}/externals/prebuilt/iosV8_openssl_3.2.1

