name: Build Assimp

on:
  workflow_dispatch:
  push:
    branches:
      - build-workflow

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Run build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_assimp_for_linux.sh v5.0.0

    - name: Archive prebuilt assimp 
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-assimp-linux
        path: ${{ github.workspace }}/externals/prebuit/linux_assimp_v5.0.0

