name: Build g2o

on:
  workflow_dispatch:
  push:
    branches:
      - build-workflow

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Run build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_g2o_x64.bat

    - name: Archive prebuilt g2o
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-g2o-windows
        path: ${{ github.workspace }}/externals/prebuild_scripts/g2o/INSTALL-vs

  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Run build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_g2o_for_linux.sh

    - name: Archive prebuilt g2o
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-g2o-linux
        path: ${{ github.workspace }}/externals/prebuilt/linux_g2o
  build-macos:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Run build script intel
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: arch -x86_64 ./build_g2o_for_mac64.sh

    - name: Run build script arm
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_g2o_for_macArm64.sh

    - name: Archive prebuilt g2o intel
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-g2o-mac64
        path: ${{ github.workspace }}/externals/prebuilt/mac64_g2o

    - name: Archive prebuilt g2o arm
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-g2o-arm64
        path: ${{ github.workspace }}/externals/prebuilt/macArm64_g2o

