name: Build Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Doxygen
      run: sudo apt install -y doxygen

    - name: Install Graphviz
      run: sudo apt install -y graphviz

    - name: Install Doxygen Awesome
      working-directory: ${{ github.workspace }}/docs
      run: git clone https://github.com/jothepro/doxygen-awesome-css.git -b v2.2.1

    - name: Run Doxygen
      working-directory: ${{ github.workspace }}/docs
      run: doxygen

    - name: Upload documentation
      working-directory: ${{ github.workspace }}/docs
      run: |
        sshpass -p "${{ secrets.EMSCRIPTEN_DEPLOY_PASSWORD }}" sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ secrets.EMSCRIPTEN_DEPLOY_REMOTE }}" << EOF
          put -r html public/www/docs
        EOF
