name: Build Windows

on:
  push:
    branches: ['main', 'develop']

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DSL_DOWNLOAD_DATA=OFF

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config Debug
