name: Build glfw

on:
  workflow_dispatch:
  push:
    branches:
      - build-workflow

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: install xrandr
      run: sudo apt-get install -y libxrandr-dev

    - name: Run build script
      working-directory: ${{ github.workspace }}/externals/prebuild_scripts/
      run: ./build_glfw_for_linux.sh 3.3.2

    - name: Archive prebuilt glfw
      uses: actions/upload-artifact@v3
      with:
        name: prebuilt-glfw-linux
        path: ${{ github.workspace }}/externals/prebuilt/linux_glfw_3.3.2



