name: Deploy Emscripten

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v11

    - name: Configure CMake
      run: emcmake cmake -B ${{ github.workspace }}/build -DSL_BUILD_WAI=OFF -DSL_BUILD_WITH_OPENSSL=OFF -DSL_DOWNLOAD_DATA=OFF -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --target app-Demo-SLProject

    - name: Upload
      uses: appleboy/scp-action@v0.1.4
      with:
        host: pallas.ti.bfh.ch
        username: github
        password: ${{ secrets.EMSCRIPTEN_DEPLOY_PASSWORD }}
        source: "${{ github.workspace }}/build/app-Demo-SLProject.html,${{ github.workspace }}/build/app-Demo-SLProject.js,${{ github.workspace }}/build/app-Demo-SLProject.wasm,${{ github.workspace }}/build/app-Demo-SLProject.worker.js"
        target: "."
        overwrite: true