name: Deploy Emscripten

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: 3.1.60

    - name: Configure CMake
      run: |
        emcmake cmake \
          -B ${{ github.workspace }}/build \
          -DSL_BUILD_WAI=OFF \
          -DSL_BUILD_WITH_OPENSSL=OFF \
          -DSL_BUILD_WITH_MEDIAPIPE=OFF \
          -DSL_DOWNLOAD_DATA=OFF \
          -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --target app-demo -j $(nproc)

    - name: Create Zip Folder
      working-directory: ${{ github.workspace }}
      run: |
        mkdir emscripten_build
        cp build/app-demo.html emscripten_build
        cp build/app-demo.js emscripten_build
        cp build/app-demo.wasm emscripten_build
        cp build/app-demo.worker.js emscripten_build

    - name: Archive emscripten_build
      uses: actions/upload-artifact@v3
      with:
        name: emscripten_build
        path: ${{ github.workspace }}/emscripten_build

# Download the artifact from the last run on https://github.com/cpvrlab/SLProject4/actions
# Unzip the emscripten_build.zip file 
# Upload the files to the public/www folder of the pallas server

    
